-- MySQL Script generated by MySQL Workbench
-- Thu Jun 24 09:37:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `idpersona` INT NOT NULL,
  `rollPersona` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dirección` VARCHAR(45) NOT NULL,
  `teléfono` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habitación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habitación` (
  `tipoHabitación` INT NOT NULL,
  `infoHabitacion` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `caracteristicas` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`tipoHabitación`),
  INDEX `fk_habitación_persona1_idx` (`persona_idpersona` ASC) ,
  CONSTRAINT `fk_habitación_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `mydb`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registroHuespedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registroHuespedes` (
  `idreserva` INT NOT NULL,
  `fechaIngreso` VARCHAR(45) NOT NULL,
  `fechaSalida` VARCHAR(45) NOT NULL,
  `cantidadPersonas` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  `habitación_tipoHabitación` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_registroHuespedes_persona_idx` (`persona_idpersona` ASC) ,
  INDEX `fk_registroHuespedes_habitación1_idx` (`habitación_tipoHabitación` ASC) ,
  CONSTRAINT `fk_registroHuespedes_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `mydb`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroHuespedes_habitación1`
    FOREIGN KEY (`habitación_tipoHabitación`)
    REFERENCES `mydb`.`habitación` (`tipoHabitación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
